name: CI
on:
- push
- pull_request
jobs:
  build:
    runs-on: ubuntu-20.04  # https://github.com/actions/setup-python/issues/544
    strategy:
      matrix:
        python-version: [2.7, 3.6, 3.7, 3.8, 3.9, pypy-2.7, pypy-3.7]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install tox tox-gh-actions 'setuptools_scm<6'
    - run: tox
